# Generated by Django 2.2 on 2019-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='al_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/image/white_board.png', max_length=256, null=True, upload_to='image', verbose_name='图像')),
                ('image_add_points', models.ImageField(blank=True, default='media/image/default.png', max_length=256, null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('image_alo', models.ImageField(blank=True, default='media/image/default.png', max_length=256, null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'al_route',
            },
        ),
        migrations.CreateModel(
            name='flr_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flr_set',
            },
        ),
        migrations.CreateModel(
            name='Lvbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image_processed', verbose_name='图像1')),
            ],
            options={
                'db_table': 'lvbo',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_spend', models.CharField(max_length=50)),
                ('money', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('isPri', models.BooleanField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeamCarvingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SeamCarving',
            },
        ),
        migrations.CreateModel(
            name='sift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image2', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sift',
            },
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fogy',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='123@163.com', max_length=128, unique=True)),
                ('Name', models.CharField(default='xxx', max_length=128)),
                ('Password', models.CharField(default='123456789', max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
