# Generated by Django 2.2 on 2019-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flr_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flr_set',
            },
        ),
        migrations.CreateModel(
            name='SeamCarvingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SeamCarving',
            },
        ),
        migrations.CreateModel(
            name='sift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image2', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sift',
            },
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_processed', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fogy',
            },
        ),
    ]
