# Generated by Django 2.2 on 2019-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='al_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/image/white_board.png', null=True, upload_to='image', verbose_name='图像')),
                ('image_add_points', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('image_alo', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/image_processed', verbose_name='图像1')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'al_route',
            },
        ),
    ]
