# Generated by Django 2.2 on 2019-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_al_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='al_route',
            name='image',
            field=models.ImageField(blank=True, default='media/image/white_board.png', max_length=256, null=True, upload_to='image', verbose_name='图像'),
        ),
        migrations.AlterField(
            model_name='al_route',
            name='image_add_points',
            field=models.ImageField(blank=True, default='media/image/default.png', max_length=256, null=True, upload_to='image/image_processed', verbose_name='图像1'),
        ),
        migrations.AlterField(
            model_name='al_route',
            name='image_alo',
            field=models.ImageField(blank=True, default='media/image/default.png', max_length=256, null=True, upload_to='image/image_processed', verbose_name='图像1'),
        ),
    ]
