# Generated by Django 2.2 on 2019-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20190508_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_spend', models.CharField(max_length=50)),
                ('money', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('isPri', models.BooleanField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
